services:
  db:
    image: postgres:15-alpine
    container_name: postgres_db
    environment:
      TZ: America/Bogota
      POSTGRES_USER: asher
      POSTGRES_PASSWORD: '12589'
      POSTGRES_DB: semillero
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  bridge:
    build: .
    container_name: esp32_bridge
    network_mode: host
    depends_on:
      - db
    environment:
      - TZ=America/Bogota
      - DATABASE_URL=postgresql://asher:12589@localhost:5432/semillero
      - VITRINA_ID=${VITRINA_ID:-1}
    volumes:
      - ./vitrinasiot-firebase-adminsdk-fbsvc-0201f15c59.json:/app/vitrinasiot-firebase-adminsdk-fbsvc-0201f15c59.json:ro
    restart: always

volumes:
  pgdata:
    driver: local
